# Generated by Django 5.2.5 on 2025-09-10 14:21

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistprofile",
            name="art_qualification",
            field=models.FileField(
                blank=True, upload_to="artist_documents/", verbose_name="艺术资质证明"
            ),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="awards_honors",
            field=models.TextField(blank=True, verbose_name="获奖荣誉"),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="education_background",
            field=models.TextField(blank=True, verbose_name="教育背景"),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="exhibition_history",
            field=models.TextField(blank=True, verbose_name="展览经历"),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="identity_document",
            field=models.FileField(
                blank=True, upload_to="artist_documents/", verbose_name="身份证明"
            ),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="other_documents",
            field=models.JSONField(default=list, verbose_name="其他证明材料"),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="portfolio_document",
            field=models.FileField(
                blank=True, upload_to="artist_documents/", verbose_name="作品集文档"
            ),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="portfolio_images",
            field=models.JSONField(default=list, verbose_name="作品集图片"),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="professional_experience",
            field=models.TextField(blank=True, verbose_name="专业经历"),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="拒绝原因"),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="review_notes",
            field=models.TextField(blank=True, verbose_name="审核备注"),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
        ),
        migrations.AddField(
            model_name="artistprofile",
            name="submitted_at",
            field=models.DateTimeField(
                auto_now_add=True, default=timezone.now, verbose_name="提交时间"
            ),
            preserve_default=False,
        ),
    ]
