# Generated by Django 5.2.5 on 2025-09-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_artistprofile_art_qualification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistprofile",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
        ),
    ]
