# Generated by Django 5.2.5 on 2025-08-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommercialCooperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200, verbose_name="公司名称")),
                (
                    "contact_person",
                    models.CharField(max_length=100, verbose_name="联系人"),
                ),
                ("contact_phone", models.CharField(max_length=20, verbose_name="联系电话")),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="联系邮箱"),
                ),
                (
                    "cooperation_type",
                    models.CharField(
                        choices=[
                            ("institutional", "机构采购"),
                            ("heritage", "非遗合作"),
                            ("creative", "文创定制"),
                            ("design", "艺术设计"),
                            ("other", "其他合作"),
                        ],
                        max_length=20,
                        verbose_name="合作类型",
                    ),
                ),
                ("project_description", models.TextField(verbose_name="项目描述")),
                (
                    "budget_range",
                    models.CharField(blank=True, max_length=100, verbose_name="预算范围"),
                ),
                (
                    "expected_timeline",
                    models.CharField(blank=True, max_length=200, verbose_name="预期时间线"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("contacted", "已联系"),
                            ("negotiating", "洽谈中"),
                            ("agreed", "已达成"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "商业合作",
                "verbose_name_plural": "商业合作",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomizationProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("design", "设计阶段"),
                            ("production", "制作阶段"),
                            ("review", "审核阶段"),
                            ("finalization", "完成阶段"),
                        ],
                        max_length=20,
                        verbose_name="阶段",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="进度标题")),
                ("description", models.TextField(verbose_name="进度描述")),
                (
                    "progress_percentage",
                    models.PositiveIntegerField(default=0, verbose_name="进度百分比"),
                ),
                ("images", models.JSONField(default=list, verbose_name="进度图片")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "定制进度",
                "verbose_name_plural": "定制进度",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomizationQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="报价"
                    ),
                ),
                ("delivery_time", models.PositiveIntegerField(verbose_name="交付时间(天)")),
                ("description", models.TextField(verbose_name="报价说明")),
                ("terms_conditions", models.TextField(blank=True, verbose_name="条款条件")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("sent", "已发送"),
                            ("accepted", "已接受"),
                            ("rejected", "已拒绝"),
                            ("expired", "已过期"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("valid_until", models.DateTimeField(verbose_name="有效期至")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "定制报价",
                "verbose_name_plural": "定制报价",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomizationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("personal", "个人定制"), ("commercial", "商业定制")],
                        max_length=20,
                        verbose_name="请求类型",
                    ),
                ),
                (
                    "customization_type",
                    models.CharField(
                        choices=[
                            ("painting", "绘画"),
                            ("sculpture", "立体艺术/雕刻"),
                            ("toy", "潮玩"),
                            ("accessory", "周边"),
                            ("handicraft", "手工艺"),
                            ("heritage", "非遗艺术"),
                        ],
                        max_length=20,
                        verbose_name="定制类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="定制标题")),
                ("description", models.TextField(verbose_name="定制描述")),
                (
                    "reference_images",
                    models.JSONField(default=list, verbose_name="参考图片"),
                ),
                (
                    "budget_range",
                    models.CharField(blank=True, max_length=100, verbose_name="预算范围"),
                ),
                (
                    "duration_type",
                    models.CharField(
                        choices=[
                            ("short", "短期订单"),
                            ("long", "长期订单"),
                            ("multiple", "多次订单"),
                        ],
                        max_length=20,
                        verbose_name="定制时间",
                    ),
                ),
                (
                    "expected_delivery",
                    models.DateField(blank=True, null=True, verbose_name="预期交付日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "定制请求",
                "verbose_name_plural": "定制请求",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomizationTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="主题名称")),
                ("description", models.TextField(blank=True, verbose_name="主题描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
            options={
                "verbose_name": "定制主题",
                "verbose_name_plural": "定制主题",
            },
        ),
    ]
