# Generated by Django 5.2.5 on 2025-08-27 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customization", "0001_initial"),
        ("products", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customizationquote",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customization_quotes",
                to="users.artistprofile",
                verbose_name="艺术家",
            ),
        ),
        migrations.AddField(
            model_name="customizationrequest",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.artistprofile",
                verbose_name="指定艺术家",
            ),
        ),
        migrations.AddField(
            model_name="customizationrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customization_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="customizationquote",
            name="customization_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="customization.customizationrequest",
                verbose_name="定制请求",
            ),
        ),
        migrations.AddField(
            model_name="customizationprogress",
            name="customization_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_updates",
                to="customization.customizationrequest",
                verbose_name="定制请求",
            ),
        ),
        migrations.AddField(
            model_name="customizationtheme",
            name="usage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customization_themes",
                to="products.usage",
                verbose_name="用途",
            ),
        ),
    ]
