# Generated by Django 5.2.5 on 2025-08-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArtistPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="作品集标题")),
                ("description", models.TextField(blank=True, verbose_name="作品集描述")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, upload_to="portfolio_covers/", verbose_name="封面图片"
                    ),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="是否公开")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "艺术家作品集",
                "verbose_name_plural": "艺术家作品集",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArtistService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("custom", "定制服务"),
                            ("consultation", "咨询服务"),
                            ("workshop", "工作坊"),
                            ("other", "其他服务"),
                        ],
                        max_length=20,
                        verbose_name="服务类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="服务标题")),
                ("description", models.TextField(verbose_name="服务描述")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="服务价格"
                    ),
                ),
                (
                    "duration",
                    models.CharField(blank=True, max_length=100, verbose_name="服务时长"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="是否可用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "艺术家服务",
                "verbose_name_plural": "艺术家服务",
            },
        ),
        migrations.CreateModel(
            name="ArtistShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(max_length=200, verbose_name="店铺名称")),
                ("shop_description", models.TextField(blank=True, verbose_name="店铺描述")),
                (
                    "shop_logo",
                    models.ImageField(
                        blank=True, upload_to="shop_logos/", verbose_name="店铺logo"
                    ),
                ),
                (
                    "shop_banner",
                    models.ImageField(
                        blank=True, upload_to="shop_banners/", verbose_name="店铺横幅"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否营业")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "艺术家店铺",
                "verbose_name_plural": "艺术家店铺",
            },
        ),
        migrations.CreateModel(
            name="ArtistTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("sale", "销售"),
                            ("refund", "退款"),
                            ("commission", "佣金"),
                            ("withdrawal", "提现"),
                        ],
                        max_length=20,
                        verbose_name="交易类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="交易金额"
                    ),
                ),
                ("description", models.TextField(verbose_name="交易描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "艺术家交易记录",
                "verbose_name_plural": "艺术家交易记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArtistWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="提现金额"
                    ),
                ),
                ("bank_account", models.CharField(max_length=100, verbose_name="银行账户")),
                ("bank_name", models.CharField(max_length=100, verbose_name="银行名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
            ],
            options={
                "verbose_name": "艺术家提现申请",
                "verbose_name_plural": "艺术家提现申请",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=100, verbose_name="客服名称")),
                ("service_type", models.CharField(max_length=50, verbose_name="服务类型")),
                ("contact_info", models.CharField(max_length=200, verbose_name="联系方式")),
                ("is_online", models.BooleanField(default=False, verbose_name="是否在线")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "客服管理",
                "verbose_name_plural": "客服管理",
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
            ],
            options={
                "verbose_name": "作品集项目",
                "verbose_name_plural": "作品集项目",
                "ordering": ["sort_order"],
            },
        ),
    ]
