# Generated by Django 5.2.5 on 2025-08-27 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("orders", "0002_initial"),
        ("products", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistportfolio",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolios",
                to="users.artistprofile",
                verbose_name="艺术家",
            ),
        ),
        migrations.AddField(
            model_name="artistservice",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="users.artistprofile",
                verbose_name="艺术家",
            ),
        ),
        migrations.AddField(
            model_name="artistshop",
            name="artist",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop",
                to="users.artistprofile",
                verbose_name="艺术家",
            ),
        ),
        migrations.AddField(
            model_name="artisttransaction",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="users.artistprofile",
                verbose_name="艺术家",
            ),
        ),
        migrations.AddField(
            model_name="artisttransaction",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.order",
                verbose_name="关联订单",
            ),
        ),
        migrations.AddField(
            model_name="artistwithdrawal",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withdrawals",
                to="users.artistprofile",
                verbose_name="艺术家",
            ),
        ),
        migrations.AddField(
            model_name="customerservice",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_services",
                to="users.artistprofile",
                verbose_name="艺术家",
            ),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="artists.artistportfolio",
                verbose_name="作品集",
            ),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
                verbose_name="商品",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="portfolioitem",
            unique_together={("portfolio", "product")},
        ),
    ]
