# Generated by Django 5.2.5 on 2025-08-27 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PriceRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="价格区间名称")),
                (
                    "min_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="最低价格"
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="最高价格",
                    ),
                ),
            ],
            options={
                "verbose_name": "价格区间",
                "verbose_name_plural": "价格区间",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="商品标题")),
                ("description", models.TextField(verbose_name="商品描述")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="原价",
                    ),
                ),
                (
                    "size",
                    models.CharField(blank=True, max_length=100, verbose_name="尺寸"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="重量(kg)",
                    ),
                ),
                ("materials", models.JSONField(default=list, verbose_name="材质")),
                ("techniques", models.JSONField(default=list, verbose_name="技法")),
                (
                    "year_created",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="创作年份"
                    ),
                ),
                ("is_original", models.BooleanField(default=True, verbose_name="是否原创")),
                ("is_limited", models.BooleanField(default=False, verbose_name="是否限量")),
                (
                    "limited_quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="限量数量"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("sold", "已售出"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/", verbose_name="图片")),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=200, verbose_name="图片描述"),
                ),
                ("is_primary", models.BooleanField(default=False, verbose_name="是否主图")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
            ],
            options={
                "verbose_name": "商品图片",
                "verbose_name_plural": "商品图片",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="标签名称"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="标签颜色"
                    ),
                ),
            ],
            options={
                "verbose_name": "商品标签",
                "verbose_name_plural": "商品标签",
            },
        ),
        migrations.CreateModel(
            name="ProductTagRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品标签关联",
                "verbose_name_plural": "商品标签关联",
            },
        ),
        migrations.CreateModel(
            name="SizeRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="尺寸区间名称")),
                (
                    "min_size",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="最小尺寸(cm³)"
                    ),
                ),
                (
                    "max_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="最大尺寸(cm³)",
                    ),
                ),
            ],
            options={
                "verbose_name": "尺寸区间",
                "verbose_name_plural": "尺寸区间",
            },
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="用途名称")),
                ("description", models.TextField(blank=True, verbose_name="用途描述")),
            ],
            options={
                "verbose_name": "用途分类",
                "verbose_name_plural": "用途分类",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="categories/", verbose_name="分类图片"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                        verbose_name="父分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品分类",
                "verbose_name_plural": "商品分类",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
